package visitorreservation.visitorreservationapi.controller.resources.interfaces.reservation;


public interface ReservationControllerInterface extends DeleteReservationResourceInterface, FindReservationResourceInterface, ListReservationResourceInterface, PostReservationResourceInterface, UpdateReservationResourceInterface {
}
