package visitorreservation.visitorreservationapi.controller.resources.interfaces.visitorReservation;

public interface VisitorReservationControllerInterface extends PostVisitorReservationResourceInterface, DeleteVisitorReservationResourceInterface{
}
