package visitorreservation.visitorreservationapi.controller.resources.interfaces.visitor;

public interface VisitorControllerInterface extends DeleteVisitorResourceInterface, FindVisitorResourceInterface, ListVisitorResourceInterface, PostVisitorResourceInterface, UpdateVisitorResourceInterface {
}
